#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from Plugins.Extensions.OpenWebif.local import tstrings

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1447321436.343035
__CHEETAH_genTimestamp__ = 'Thu Nov 12 18:43:56 2015'
__CHEETAH_src__ = '/home/knuth/openpli-oe-core/build/tmp/work/fusionhd-oe-linux/enigma2-plugin-extensions-openwebif/1+gitAUTOINC+5837c87afc-r0/git/plugin/controllers/views/mobile/control.tmpl'
__CHEETAH_srcLastModified__ = 'Thu Nov 12 18:43:41 2015'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class control(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(control, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''<html>\r
 <head>\r
\t<title>OpenWebif</title>\r
\t<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />\r
\t<meta name="viewport" content="user-scalable=no, width=device-width"/>\r
\t<meta name="apple-mobile-web-app-capable" content="yes" />\r
\t<link rel="stylesheet" type="text/css" href="/css/jquery.mobile-1.0.min.css" media="screen"/>\r
\t<link rel="stylesheet" type="text/css" href="/css/iphone.css" media="screen"/>\r
\t<script src="/js/jquery-1.6.2.min.js"></script>\r
\t<script src="/js/jquery.mobile-1.0.min.js"></script>\r
 </head>\r
 <body>\r
\t<div data-role="page" id="mainPage">\r
\t\t<div id="header">\r
\t\t\t<div class="button" onClick="history.back()">''')
        _v = VFFSL(SL,"tstrings",True)['back'] # u"$tstrings['back']" on line 16, col 49
        if _v is not None: write(_filter(_v, rawExpr=u"$tstrings['back']")) # from line 16, col 49.
        write(u'''</div>\r
\t\t\t<h1><a style="color:#FFF;text-decoration:none;" href=\'/mobile\'>OpenWebif</a></h1>
\t\t</div>\r
\t\t\r
\t\t<div id="contentContainer">\r
\t\t\t<ul data-role="listview" data-inset="true" data-theme="d">\r
\t\t\t\t<li data-role="list-divider" role="heading" data-theme="b">''')
        _v = VFFSL(SL,"tstrings",True)['volumecontrol'] # u"$tstrings['volumecontrol']" on line 22, col 64
        if _v is not None: write(_filter(_v, rawExpr=u"$tstrings['volumecontrol']")) # from line 22, col 64.
        write(u'''</li>\r
\t\t\t\t<li>\r
\t\t\t\t\t<table width="100%">\r
\t\t\t\t\t\t<tr>\r
\t\t\t\t\t\t\t<td><input type="range" name="slider" id="slider" value="0" min="0" max="100" data-theme="a" data-track-theme="b" /></td>\r
\t\t\t\t\t\t\t<td width="50"><img id="volimage" src="/images/volume.png" border="0" alt="" /></td>\r
\t\t\t\t\t\t</tr>\r
\t\t\t\t\t</table>\r
\t\t\t\t</li>\r
\t\t\t</ul>\r
\t\t\t\r
\t\t\t<br><br>\r
\r
\t\t\t<ul data-role="listview" data-inset="true" data-theme="d">\r
\t\t\t\t<li data-role="list-divider" role="heading" data-theme="b">''')
        _v = VFFSL(SL,"tstrings",True)['instant_record'] # u"$tstrings['instant_record']" on line 36, col 64
        if _v is not None: write(_filter(_v, rawExpr=u"$tstrings['instant_record']")) # from line 36, col 64.
        write(u'''</li>\r
\t\t\t\t<li><a href="#" onClick="startInstantRecord()">''')
        _v = VFFSL(SL,"tstrings",True)['start_instant_record'] # u"$tstrings['start_instant_record']" on line 37, col 52
        if _v is not None: write(_filter(_v, rawExpr=u"$tstrings['start_instant_record']")) # from line 37, col 52.
        write(u'''</a></li>\r
\t\t\t</ul>\r
\t\t\t\r
\t\t\t<br><br>\r
\t\t\t\r
\t\t\t<ul data-role="listview" data-inset="true" data-theme="d">\r
\t\t\t\t<li data-role="list-divider" role="heading" data-theme="b">''')
        _v = VFFSL(SL,"tstrings",True)['powercontrol'] # u"$tstrings['powercontrol']" on line 43, col 64
        if _v is not None: write(_filter(_v, rawExpr=u"$tstrings['powercontrol']")) # from line 43, col 64.
        write(u'''</li>\r
\t\t\t\t<li><a href="#" onClick="jQuery.ajax(\'/api/powerstate?newstate=0\'); return false">''')
        _v = VFFSL(SL,"tstrings",True)['standby_toggle'] # u"$tstrings['standby_toggle']" on line 44, col 87
        if _v is not None: write(_filter(_v, rawExpr=u"$tstrings['standby_toggle']")) # from line 44, col 87.
        write(u'''</a></li>\r
\t\t\t\t<li><a href="#" onClick="jQuery.ajax(\'/api/powerstate?newstate=1\'); return false">''')
        _v = VFFSL(SL,"tstrings",True)['deep_standby'] # u"$tstrings['deep_standby']" on line 45, col 87
        if _v is not None: write(_filter(_v, rawExpr=u"$tstrings['deep_standby']")) # from line 45, col 87.
        write(u'''</a></li>\r
\t\t\t\t<li><a href="#" onClick="jQuery.ajax(\'/api/powerstate?newstate=2\'); return false">''')
        _v = VFFSL(SL,"tstrings",True)['reboot_box'] # u"$tstrings['reboot_box']" on line 46, col 87
        if _v is not None: write(_filter(_v, rawExpr=u"$tstrings['reboot_box']")) # from line 46, col 87.
        write(u'''</a></li>\r
\t\t\t\t<li><a href="#" onClick="jQuery.ajax(\'/api/powerstate?newstate=3\'); return false">''')
        _v = VFFSL(SL,"tstrings",True)['restart_gui'] # u"$tstrings['restart_gui']" on line 47, col 87
        if _v is not None: write(_filter(_v, rawExpr=u"$tstrings['restart_gui']")) # from line 47, col 87.
        write(u'''</a></li>\r
\t\t\t</ul>\r
\t\t</div>\r
\t\t\r
\t\t<div id="footer">\r
\t\t\t<p>OpenWebif Mobile</p>\r
\t\t\t<a onclick="document.location.href=\'/index?mode=fullpage\';return false;" href="#">''')
        _v = VFFSL(SL,"tstrings",True)['show_full_openwebif'] # u"$tstrings['show_full_openwebif']" on line 53, col 86
        if _v is not None: write(_filter(_v, rawExpr=u"$tstrings['show_full_openwebif']")) # from line 53, col 86.
        write(u'''</a>\r
\t\t</div>\r
\t\t\r
\t<script>\r
\tfunction getStatusInfo() {\r
\t\tjQuery.getJSON(\'/api/statusinfo\')\r
\t\t.success(function(statusinfo) {\r
\t\t\t// Set Volume\r
\t\t\tjQuery("#slider").val(statusinfo[\'volume\']).slider(\'refresh\');\r
\r
\t\t\t// Set Mute Status\r
\t\t\tif (statusinfo[\'muted\'] == true) {\r
\t\t\t\tmutestatus = 1;\r
\t\t\t\tjQuery("#volimage").attr("src","/images/volume_mute.png");\r
\t\t\t} else {\r
\t\t\t\tmutestatus = 0;\r
\t\t\t\tjQuery("#volimage").attr("src","/images/volume.png");\r
\t\t\t}\r
\t\t});\r
\t}\r
\r
\tfunction setVolume(vol) {\r
\t\tvar jqxhr = jQuery.ajax("/web/vol?set=set" + vol);\r
\t\treturn false;\r
\t}\r
\t\r
\tfunction startInstantRecord(vol) {\r
\t\tcheck = confirm("Really start instant record now?");\r
\t\tif (check == true) {\r
\t\t\tjQuery.ajax(\'/api/recordnow\');\r
\t\t}\r
\t\treturn false;\r
\t}\r
\t\r
\tjQuery(\'#mainPage\').live(\'pageinit\', function(event) {\r
\t\tvar volupdate;\r
\t\tjQuery("#slider").change(function() {\r
\t\t\tclearTimeout(volupdate);\r
\t\t\tvolupdate = setTimeout("jQuery.ajax(\'/web/vol?set=set" + jQuery(\'#slider\').val() + "\')",1000);\r
\t\t});\r
\t\t\r
\t\tvar mutestatus = 0;\r
\t\tjQuery(\'#volimage\').click(function(){\r
\t\t\tif (mutestatus == 0) {\r
\t\t\t\tmutestatus = 1;\r
\t\t\t\tjQuery("#volimage").attr("src","/images/volume_mute.png");\r
\t\t\t} else  {\r
\t\t\t\tmutestatus = 0;\r
\t\t\t\tjQuery("#volimage").attr("src","/images/volume.png");\r
\t\t\t}\r
\t\t\tjQuery.ajax("/web/vol?set=mute")\r
\t\t});\r
\t\t\r
\t\tgetStatusInfo();\r
\t});\r
\t</script>\r
\t</div>\r
 </body>\r
</html>\r
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_control= 'respond'

## END CLASS DEFINITION

if not hasattr(control, '_initCheetahAttributes'):
    templateAPIClass = getattr(control, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(control)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=control()).run()


