#!/usr/bin/env python




##################################################
## DEPENDENCIES
import sys
import os
import os.path
try:
    import builtins as builtin
except ImportError:
    import __builtin__ as builtin
from os.path import getmtime, exists
import time
import types
from Cheetah.Version import MinCompatibleVersion as RequiredCheetahVersion
from Cheetah.Version import MinCompatibleVersionTuple as RequiredCheetahVersionTuple
from Cheetah.Template import Template
from Cheetah.DummyTransaction import *
from Cheetah.NameMapper import NotFound, valueForName, valueFromSearchList, valueFromFrameOrSearchList
from Cheetah.CacheRegion import CacheRegion
import Cheetah.Filters as Filters
import Cheetah.ErrorCatchers as ErrorCatchers
from urllib import quote
from Plugins.Extensions.OpenWebif.local import tstrings

##################################################
## MODULE CONSTANTS
VFFSL=valueFromFrameOrSearchList
VFSL=valueFromSearchList
VFN=valueForName
currentTime=time.time
__CHEETAH_version__ = '2.4.4'
__CHEETAH_versionTuple__ = (2, 4, 4, 'development', 0)
__CHEETAH_genTime__ = 1447321436.588084
__CHEETAH_genTimestamp__ = 'Thu Nov 12 18:43:56 2015'
__CHEETAH_src__ = '/home/knuth/openpli-oe-core/build/tmp/work/fusionhd-oe-linux/enigma2-plugin-extensions-openwebif/1+gitAUTOINC+5837c87afc-r0/git/plugin/controllers/views/ajax/bouquets.tmpl'
__CHEETAH_srcLastModified__ = 'Thu Nov 12 18:43:41 2015'
__CHEETAH_docstring__ = 'Autogenerated by Cheetah: The Python-Powered Template Engine'

if __CHEETAH_versionTuple__ < RequiredCheetahVersionTuple:
    raise AssertionError(
      'This template was compiled with Cheetah version'
      ' %s. Templates compiled before version %s must be recompiled.'%(
         __CHEETAH_version__, RequiredCheetahVersion))

##################################################
## CLASSES

class bouquets(Template):

    ##################################################
    ## CHEETAH GENERATED METHODS


    def __init__(self, *args, **KWs):

        super(bouquets, self).__init__(*args, **KWs)
        if not self._CHEETAH__instanceInitialized:
            cheetahKWArgs = {}
            allowedKWs = 'searchList namespaces filter filtersLib errorCatcher'.split()
            for k,v in KWs.items():
                if k in allowedKWs: cheetahKWArgs[k] = v
            self._initCheetahInstance(**cheetahKWArgs)
        

    def respond(self, trans=None):



        ## CHEETAH: main method generated for this template
        if (not trans and not self._CHEETAH__isBuffering and not callable(self.transaction)):
            trans = self.transaction # is None unless self.awake() was called
        if not trans:
            trans = DummyTransaction()
            _dummyTrans = True
        else: _dummyTrans = False
        write = trans.response().write
        SL = self._CHEETAH__searchList
        _filter = self._CHEETAH__currentFilter
        
        ########################################
        ## START - generated method body
        
        write(u'''<script>
$(function() { InitAccordeon("#accordion");});
</script>
<div id="accordion">
''')
        for bouquet in VFFSL(SL,"bouquets",True): # generated from line 7, col 1
            write(u'''<h1>
<div>
<div class="ow_i ow_i_stream1" onclick="window.open(\'web/services.m3u?bRef=''')
            _v = VFFSL(SL,"quote",False)(VFFSL(SL,"bouquet",True)[0]) # u'$quote($bouquet[0])' on line 10, col 76
            if _v is not None: write(_filter(_v, rawExpr=u'$quote($bouquet[0])')) # from line 10, col 76.
            write(u'''\',\'_blank\');return false;" style="margin-left:30px;margin-bottom:-3px;" title="''')
            _v = VFFSL(SL,"tstrings",True)['download_playlist'] # u"$tstrings['download_playlist']" on line 10, col 174
            if _v is not None: write(_filter(_v, rawExpr=u"$tstrings['download_playlist']")) # from line 10, col 174.
            write(u''' ''')
            _v = VFFSL(SL,"bouquet",True)[1] # u'$bouquet[1]' on line 10, col 205
            if _v is not None: write(_filter(_v, rawExpr=u'$bouquet[1]')) # from line 10, col 205.
            write(u'''" ></div>
<a style="display: inline-block;" href="#" id="ajax/channels?id=''')
            _v = VFFSL(SL,"quote",False)(VFFSL(SL,"bouquet",True)[0]) # u'$quote($bouquet[0])' on line 11, col 65
            if _v is not None: write(_filter(_v, rawExpr=u'$quote($bouquet[0])')) # from line 11, col 65.
            write(u'''&stype=''')
            _v = VFFSL(SL,"stype",True) # u'$stype' on line 11, col 91
            if _v is not None: write(_filter(_v, rawExpr=u'$stype')) # from line 11, col 91.
            write(u'''">''')
            _v = VFFSL(SL,"bouquet",True)[1] # u'$bouquet[1]' on line 11, col 99
            if _v is not None: write(_filter(_v, rawExpr=u'$bouquet[1]')) # from line 11, col 99.
            write(u'''</a>
</div></h1><div>''')
            _v = VFFSL(SL,"tstrings",True)["loading"] # u'$tstrings["loading"]' on line 12, col 17
            if _v is not None: write(_filter(_v, rawExpr=u'$tstrings["loading"]')) # from line 12, col 17.
            write(u''' ...</div>
''')
        write(u'''</div>
''')
        
        ########################################
        ## END - generated method body
        
        return _dummyTrans and trans.response().getvalue() or ""
        
    ##################################################
    ## CHEETAH GENERATED ATTRIBUTES


    _CHEETAH__instanceInitialized = False

    _CHEETAH_version = __CHEETAH_version__

    _CHEETAH_versionTuple = __CHEETAH_versionTuple__

    _CHEETAH_genTime = __CHEETAH_genTime__

    _CHEETAH_genTimestamp = __CHEETAH_genTimestamp__

    _CHEETAH_src = __CHEETAH_src__

    _CHEETAH_srcLastModified = __CHEETAH_srcLastModified__

    _mainCheetahMethod_for_bouquets= 'respond'

## END CLASS DEFINITION

if not hasattr(bouquets, '_initCheetahAttributes'):
    templateAPIClass = getattr(bouquets, '_CHEETAH_templateClass', Template)
    templateAPIClass._addCheetahPlumbingCodeToClass(bouquets)


# CHEETAH was developed by Tavis Rudd and Mike Orr
# with code, advice and input from many other volunteers.
# For more information visit http://www.CheetahTemplate.org/

##################################################
## if run from command line:
if __name__ == '__main__':
    from Cheetah.TemplateCmdLineIface import CmdLineIface
    CmdLineIface(templateObj=bouquets()).run()


